### ISSUE TITLE
Is it possible to rearrange nodes in source json

### ISSUE THREAD

**Issue by zhaomuzhi** [microsoft/json-document-transforms#14]
Considering this example, I have a json that looks like this 
``` json
{
    "root": {
        "second-level":{
            "third-level":[1,2,3,4]
        }
    }
}
```
If I want to move the value of "third-level" up to the second level, like this
``` json
{
    "root": {
        "second-level":[1,2,3,4]
    }
}
```
How should I write the transform string, or is it supported?

**Comment by davilimap** [comment]
A direct move like this is currently not supported. Right now you would have to replace the second level with the contents you want. So for this case the transform file would look something like:
``` json
{
   "root": {
      "second-level": [1, 2, 3, 4]
   }
}
```
